```{r include=FALSE}
#packages
library(knitr)
library(dplyr)
library(flextable)
library(magrittr)
library(kableExtra)
library(tidytext)
library(tidyverse)
library(plot.matrix)
library(stringr)
library(micropan)
library(ggpubr)
library(highcharter)
library(ggpubr)
library(tm)
library("SnowballC")
library("wordcloud")
library("RColorBrewer")
library(wordcloud2)
library(e1071)
library(nnet)
library(rpart)
library(randomForest)
library(GGally)
library(ggrepel)
library(Hmisc)
library(corrplot)
```

# EDA
```{r}
ggpairs(mu_feat,
        columns = 19:28,
        aes(color = label, alpha = 1),
        upper = "blank")
ggsave("D:/music_feature/fig/ggpairs3.png")
```

```{r}
x      = mu_feat[,1:28]

#x      = x[,3:ncol(x)] 
n      = nrow(x)
p      = ncol(x)

one    = matrix(1,n,n)
h      = diag(1,n,n)-one/n             #centering the matrix
a      = x-matrix(apply(x,2,mean),n,p,byrow=T) #substracts mean
d      = diag(1/sqrt(colSums(a^2)/n))

xs     = h%*%as.matrix(x)%*%d         #standardized data
xs1    = xs/sqrt(n)
xs2    = t(xs1)%*%xs1

eig    = eigen(xs2) #spectral decomposition
lambda = eig$values
gamma  = eig$vectors

w      = gamma*(matrix(sqrt(lambda),nrow=nrow(gamma),ncol=ncol(gamma),byrow=T)) #coordinates of food
w      = w[,1:2]  
w      = round(w,3)

z1     = xs1%*%gamma #coordinates of families
z2     = sqrt(n/p)*z1 
z      = z2[,1:2] 
z      = round(z,3)

namew  = feat
namez  = rownames(mu_feat)

par(mfrow=c(2,2))
plot(w[,1],-w[,2],type="n",xlab="W[,1]",ylab="W[,2]",main="feature",cex.axis=1.2,cex.lab=1.2,cex.main=1.6,xlim=c(-1.2,1.2),ylim=c(-1,1))
text(w[,1],-w[,2],namew,xpd=NA)
abline(h=0,v=0,lwd=1.2)

for (i in 1:7){
	mtext(namew[i],side=1,line=5+i,at=-1.15)
 	mtext(toString(c(sprintf("%.3f",w[i,1]))),side=1,line=5+i,at=-.55)
 	mtext(toString(c(sprintf("%.3f",w[i,2]))),side=1,line=5+i,at=0)
 	}

plot(z[,1],-z[,2],type="n",xlim=c(-2,2),ylim=c(-1.1,1),xlab="Z[,1]",ylab="Z[,2]",main="Families",cex.axis=1.2,cex.lab=1.2,cex.main=1.6)
text(z[,1],-z[,2],namez,xpd=NA)
abline(h=0,v=0,lwd=1.2)

for (i in 1:12){
	mtext(namez[i],side=1,line=5+i,at=-2)
 	mtext(toString(c(sprintf("%.3f",z[i,1]))),side=1,line=5+i,at=-1)
 	mtext(toString(c(sprintf("%.3f",z[i,2]))),side=1,line=5+i,at=-0)
 	}
```

```{r}
pca = cbind(w[,1],-w[,2])
pca = cbind(pca,feat)
pca = as.data.frame(pca)
rownames(pca) = feat
colnames(pca) = c('PC1', 'PC2', 'feat')
```

```{r}
pcaplot <- ggplot(pca, aes(x= PC1, y= PC2)) + 
  geom_point(color = "blue", size = 3)+
  theme(legend.position="none")

### geom_label_repel
pcaplot + 
  geom_label_repel(aes(label = feat),
                  segment.color = 'grey50') +
  theme_classic()

ggsave("D:/music_feature/fig/pca_feat.png")
```

```{r}
res2<-rcorr(as.matrix(mu_feat[,1:28]))
flattenCorrMatrix(res2$r, res2$P)
```

```{r}
corrplot(res2$r, type="upper", order="hclust", 
         p.mat = res2$P, sig.level = 0.01, insig = "blank")
```

```{r}
col<- colorRampPalette(c("blue", "white", "red"))(20)
heatmap(x = res2$r, col = col, symm = TRUE)
```